# user/password: admin@example.com/changeme
services:
  npm:
    container_name: npm
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    # networks:
    #   - mynetwork
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
# networks:
#   mynetwork:
#     external: true