services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    # networks:
    #   - mynetwork
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    command: tunnel --no-autoupdate run --token ${TOKEN}
# networks:
#   mynetwork:
#     external: true